
language: go

sudo: false

go:
  - 1.7
  - tip

install:
  - go get github.com/google/badwolf/...
  - go get github.com/boltdb/bolt
  - go get golang.org/x/net/context

script:
  - go test -v -race ./...
